In [43]:
import pandas as pd
import numpy as np

In [2]:
df = pd.read_csv('https://raw.githubusercontent.com/alexeygrigorev/datasets/master/car_fuel_efficiency.csv')

In [3]:
df.head()

,engine_displacement,num_cylinders,horsepower,vehicle_weight,acceleration,model_year,origin,fuel_type,drivetrain,num_doors,fuel_efficiency_mpg
0,170,3.0,159.0,3413.433759,17.7,2003,Europe,Gasoline,All-wheel drive,0.0,13.231729
1,130,5.0,97.0,3149.664934,17.8,2007,USA,Gasoline,Front-wheel drive,0.0,13.688217
2,170,NaN,78.0,3079.038997,15.1,2018,Europe,Gasoline,Front-wheel drive,0.0,14.246341
3,220,4.0,NaN,2542.392402,20.2,2009,USA,Diesel,All-wheel drive,2.0,16.912736
4,210,1.0,140.0,3460.870990,14.4,2009,Europe,Gasoline,All-wheel drive,2.0,12.488369

## Q1. Pandas version

In [8]:
pd.__version__

'3.0.3'

## Q2. How many records are in the dataset? 9704

In [9]:
df.describe()

,engine_displacement,num_cylinders,horsepower,vehicle_weight,acceleration,model_year,num_doors,fuel_efficiency_mpg
count,9704.000000,9222.000000,8996.000000,9704.000000,8774.000000,9704.000000,9202.000000,9704.000000
mean,199.708368,3.962481,149.657292,3001.280993,15.021928,2011.484027,-0.006412,14.985243
std,49.455319,1.999323,29.879555,497.894860,2.510339,6.659808,1.048162,2.556468
min,10.000000,0.000000,37.000000,952.681761,6.000000,2000.000000,-4.000000,6.200971
25%,170.000000,3.000000,130.000000,2666.248985,13.300000,2006.000000,-1.000000,13.267459
50%,200.000000,4.000000,149.000000,2993.226296,15.000000,2012.000000,0.000000,15.006037
75%,230.000000,5.000000,170.000000,3334.957039,16.700000,2017.000000,1.000000,16.707965
max,380.000000,13.000000,271.000000,4739.077089,24.300000,2023.000000,4.000000,25.967222

## Q3. Fuel types
How many fuel types are presented in the dataset? A: 2

In [10]:
df.fuel_type.value_counts()

fuel_type
Gasoline    4898
Diesel      4806
Name: count, dtype: int64

## Q4. Missing values
How many columns in the dataset have missing values? A: 4

In [12]:
df.isnull().sum()

engine_displacement      0
num_cylinders          482
horsepower             708
vehicle_weight           0
acceleration           930
model_year               0
origin                   0
fuel_type                0
drivetrain               0
num_doors              502
fuel_efficiency_mpg      0
dtype: int64

## Q5. Max fuel efficiency
What's the maximum fuel efficiency of cars from Asia? A: 23.75

In [15]:
df[df['origin']=='Asia'].describe()

,engine_displacement,num_cylinders,horsepower,vehicle_weight,acceleration,model_year,num_doors,fuel_efficiency_mpg
count,3247.000000,3099.000000,3013.000000,3247.000000,2933.000000,3247.000000,3072.000000,3247.000000
mean,200.052356,4.010326,150.303352,3006.292228,15.036754,2011.489375,-0.001628,14.973830
std,49.287252,1.971199,30.257169,502.434626,2.488340,6.704607,1.051428,2.578345
min,30.000000,0.000000,40.000000,1223.298226,6.400000,2000.000000,-4.000000,6.886245
25%,170.000000,3.000000,130.000000,2665.518985,13.300000,2006.000000,-1.000000,13.252010
50%,200.000000,4.000000,150.000000,2988.585737,15.100000,2012.000000,0.000000,15.034670
75%,230.000000,5.000000,171.000000,3345.355571,16.700000,2017.000000,1.000000,16.726318
max,370.000000,11.000000,245.000000,4661.144932,22.700000,2023.000000,4.000000,23.759123

## Q6. Median value of horsepower
1. Find the median value of the horsepower column in the dataset.
2. Next, calculate the most frequent value of the same horsepower column.
3. Use the fillna method to fill the missing values in the horsepower column with the most frequent value from the previous step.
4. Now, calculate the median value of horsepower once again.

Has it changed? A: Yes, it increased

In [16]:
df['horsepower'].median()

np.float64(149.0)

In [18]:
df['horsepower'].describe()

count    8996.000000
mean      149.657292
std        29.879555
min        37.000000
25%       130.000000
50%       149.000000
75%       170.000000
max       271.000000
Name: horsepower, dtype: float64

In [27]:
df['horsepower'].value_counts()

horsepower
152.0    142
145.0    141
151.0    134
148.0    130
141.0    130
        ...
40.0       1
57.0       1
245.0      1
252.0      1
61.0       1
Name: count, Length: 192, dtype: int64

In [28]:
df['horsepower']=df['horsepower'].fillna(value=152)

In [29]:
df['horsepower'].median()

np.float64(152.0)

In [30]:
df['horsepower'].isnull().sum()

np.int64(0)

## Q7. Sum of weights A: 0.51
1. Select all the cars from Asia
2. Select only the columns vehicle_weight and model_year
3. Select the first 7 values
4. Get the underlying NumPy array. Let's call it X.
5. Compute matrix-matrix multiplication between the transpose of X and X. To get the transpose, use X.T. Let's call the result XTX.
6. Invert XTX.
7. Create an array y with values [1100, 1300, 800, 900, 1000, 1100, 1200].
8. Multiply the inverse of XTX with the transpose of X, and then multiply the result by y. Call the result w.
What's the sum of all the elements of the result?
Note: You just implemented linear regression. We'll talk about it in the next lesson.

In [31]:
df = df[df['origin']=='Asia']

In [32]:
df = df[['vehicle_weight','model_year']]

In [33]:
df.head()

    vehicle_weight  model_year
8      2714.219310        2016
12     2783.868974        2010
14     3582.687368        2007
20     2231.808142        2011
21     2659.431451        2016

In [34]:
df = df.head(7)

In [35]:
df

    vehicle_weight  model_year
8      2714.219310        2016
12     2783.868974        2010
14     3582.687368        2007
20     2231.808142        2011
21     2659.431451        2016
34     2844.227534        2014
38     3761.994038        2019

In [36]:
X = df.values

In [37]:
X

array([[2714.21930965, 2016.        ],
       [2783.86897424, 2010.        ],
       [3582.68736772, 2007.        ],
       [2231.8081416 , 2011.        ],
       [2659.43145076, 2016.        ],
       [2844.22753389, 2014.        ],
       [3761.99403819, 2019.        ]])

In [65]:
XTX = X.T.dot(X)

In [66]:
XTX

array([[62248334.33150762, 41431216.5073268 ],
       [41431216.5073268 , 28373339.        ]])

In [68]:
XTX_inv = np.linalg.inv(XTX)
XTX_inv

array([[ 5.71497081e-07, -8.34509443e-07],
       [-8.34509443e-07,  1.25380877e-06]])

In [46]:
y = np.array([1100, 1300, 800, 900, 1000, 1100, 1200])

In [69]:
z= XTX_inv.dot(X.T)

In [70]:
z

array([[-1.31202622e-04, -8.63909858e-05,  3.72634923e-04,
        -4.02726650e-04, -1.62513724e-04, -5.52342829e-05,
         4.65094049e-04],
       [ 2.62636846e-04,  1.96990690e-04, -4.73392228e-04,
         6.58944477e-04,  3.08357831e-04,  1.51636137e-04,
        -6.07979633e-04]])

In [74]:
w = z.dot(y)

In [75]:
w

array([0.01386421, 0.5049067 ])

In [76]:
result = 0.0
for i in w:
    result = result + i

In [77]:
result

np.float64(0.5187709081074016)